name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive test-results
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Test-Results
        path: core/build/reports/tests/allTests
    - name: Archive server log
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Server-Logs
        path: test-server/build/server.log
    - name: Publish with Gradle
      run: ./gradlew publish
      env: # Or as an environment variable
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}