name: release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew core:publish
        env: # Or as an environment variable
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      - name: Generating API docs
        run: ./gradlew dokka
      - name: Updating Github Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          repo: jwstegemann/fritz2-api 
          target_branch: master
          keep_history: false
          build_dir: api/dokka
        env:
          GITHUB_PAT: ${{ secrets.FRITZ2_DOKKA_TOKEN }}
