name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish with Gradle
        run: ./gradlew publish
        env: # Or as an environment variable
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Generating API docs
        run: ./gradlew dokkaHtmlMultiModule

      - name: Build Demos
        run: ./gradlew build metadataToWww

      - name: Build Webpage
        working-directory: ./www
        run: export NODE_OPTIONS=--openssl-legacy-provider && npm install && npm run build

      - name: Copy api docs to webpage
        run: mkdir -p ./www/_site/api && cp -r ./api/* ./www/_site/api

      - name: Copy headless-demo files to webpage
        run: mkdir -p ./www/_site/headless-demo && cp ./headless-demo/build/dist/js/productionExecutable/* ./www/_site/headless-demo

      - name: Copy snippets files to webpage
        run: mkdir -p ./www/_site/snippets && cp ./snippets/build/dist/js/productionExecutable/* ./www/_site/snippets

      - name: Copy example distributions to webpage
        run: >
          for directory in `ls ./examples/* -d`; do
            name=`basename $directory`;
            mkdir -p ./www/_site/examples/$name;
            cp ./examples/$name/build/dist/js/productionExecutable/* ./www/_site/examples/$name;
          done

      - name: Releasing www page
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: jwstegemann/fritz2-web
          target_branch: master
          keep_history: false
          jekyll: false
          fqdn: www.fritz2.dev
          build_dir: ./www/_site
        env:
          GH_PAT: ${{ secrets.FRITZ2_WEB_TOKEN }}
