name: publish www

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set up Nodejs 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generating API docs
        run: ./gradlew dokkaHtmlMultiModule

      - name: Build Demos
        run: ./gradlew build metadataToWww

      - name: Build Webpage
        working-directory: ./www
        run: export NODE_OPTIONS=--openssl-legacy-provider && npm install && npm run build

      - name: Copy api docs to webpage
        run: mkdir -p ./www/_site/api && cp -r ./api/* ./www/_site/api

      - name: Copy headless-demo files to webpage
        run: mkdir -p ./www/_site/headless-demo && cp ./headless-demo/build/dist/js/productionExecutable/* ./www/_site/headless-demo

      - name: Copy snippets files to webpage
        run: mkdir -p ./www/_site/snippets && cp ./snippets/build/dist/js/productionExecutable/* ./www/_site/snippets

      - name: Copy example distributions to webpage
        run: >
          for directory in `ls ./examples/* -d`; do
            name=`basename $directory`;
            mkdir -p ./www/_site/examples/$name;
            cp ./examples/$name/build/dist/js/productionExecutable/* ./www/_site/examples/$name;
          done

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          jekyll: false
          fqdn: next.fritz2.dev
          build_dir: ./www/_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}